package bindgen

import (
	"bytes"
	"fmt"
	"go/types"
	"strings"

	"github.com/zackarysantana/sash/src/config"
)

func renderClientJS(typeName string, methods []signatureMethod, embeddedMount, devAPIBase string) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by \"sash bind\"; DO NOT EDIT.\n\n")

	fmt.Fprintf(&b, "let __sashCfg = {};\n\n")

	fmt.Fprintf(&b, "export function configureSashBindings(c) {\n")
	fmt.Fprintf(&b, "  __sashCfg = { ...__sashCfg, ...c };\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "const embeddedMount = %q;\n", embeddedMount)
	fmt.Fprintf(&b, "export const devApiBaseURL = %q;\n\n", devAPIBase)

	fmt.Fprintf(&b, "function rpcUrl(method) {\n")
	fmt.Fprintf(&b, "  const base = (__sashCfg.apiBase ?? \"\").replace(/\\/+$/, \"\");\n")
	fmt.Fprintf(&b, "  const suffix = `/API/${method}`;\n")
	fmt.Fprintf(&b, "  if (base !== \"\") {\n")
	fmt.Fprintf(&b, "    return `${base}${suffix}`;\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "  return `${embeddedMount}${suffix}`;\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "export function eventsURL() {\n")
	fmt.Fprintf(&b, "  const base = (__sashCfg.apiBase ?? \"\").replace(/\\/+$/, \"\");\n")
	fmt.Fprintf(&b, "  if (base !== \"\") {\n")
	fmt.Fprintf(&b, "    return `${base}/events`;\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "  return `${embeddedMount}/events`;\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "async function rpcCall(method, args, fetchOpts) {\n")
	fmt.Fprintf(&b, "  const res = await fetch(rpcUrl(method), {\n")
	fmt.Fprintf(&b, "    method: \"POST\",\n")
	fmt.Fprintf(&b, "    headers: { \"Content-Type\": \"application/json\" },\n")
	fmt.Fprintf(&b, "    body: JSON.stringify({ args }),\n")
	fmt.Fprintf(&b, "    signal: fetchOpts?.signal,\n")
	fmt.Fprintf(&b, "  });\n")
	fmt.Fprintf(&b, "  let body = {};\n")
	fmt.Fprintf(&b, "  try {\n")
	fmt.Fprintf(&b, "    body = await res.json();\n")
	fmt.Fprintf(&b, "  } catch {\n")
	fmt.Fprintf(&b, "    body = {};\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "  if (!res.ok || body.error) {\n")
	fmt.Fprintf(&b, "    throw new Error(body.error ?? res.statusText);\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "  if (\"result\" in body) {\n")
	fmt.Fprintf(&b, "    return body.result;\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "  return undefined;\n")
	fmt.Fprintf(&b, "}\n\n")

	probePath := embeddedMount + "/API/" + methods[0].Name
	fmt.Fprintf(&b, "async function __sashAutoConfigureRuntime() {\n")
	fmt.Fprintf(&b, "  if (typeof globalThis.location === \"undefined\") {\n")
	fmt.Fprintf(&b, "    return;\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "  if (__sashCfg.apiBase) {\n")
	fmt.Fprintf(&b, "    return;\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "  if (typeof import.meta !== \"undefined\" && import.meta.env && import.meta.env.DEV === true) {\n")
	fmt.Fprintf(&b, "    configureSashBindings({ apiBase: devApiBaseURL });\n")
	fmt.Fprintf(&b, "    return;\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "  try {\n")
	fmt.Fprintf(&b, "    const res = await fetch(new URL(%q, globalThis.location.href), { method: \"OPTIONS\" });\n", probePath)
	fmt.Fprintf(&b, "    if (res.ok) {\n")
	fmt.Fprintf(&b, "      return;\n")
	fmt.Fprintf(&b, "    }\n")
	fmt.Fprintf(&b, "  } catch (_) {}\n")
	fmt.Fprintf(&b, "  configureSashBindings({ apiBase: devApiBaseURL });\n")
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "await __sashAutoConfigureRuntime();\n\n")

	fmt.Fprintf(&b, "export const %s = {\n", typeName)
	for _, m := range methods {
		argDecl := make([]string, len(m.ParamTypes))
		for i := range m.ParamTypes {
			argDecl[i] = fmt.Sprintf("a%d", i)
		}
		argList := strings.Join(argDecl, ", ")
		callList := strings.Join(argDecl, ", ")
		switch m.ResultKind {
		case "error":
			if argList != "" {
				fmt.Fprintf(&b, "  async %s(%s, fetchOpts) {\n", m.Name, argList)
				fmt.Fprintf(&b, "    await rpcCall(%q, [%s], fetchOpts);\n", m.Name, callList)
			} else {
				fmt.Fprintf(&b, "  async %s(fetchOpts) {\n", m.Name)
				fmt.Fprintf(&b, "    await rpcCall(%q, [], fetchOpts);\n", m.Name)
			}
			fmt.Fprintf(&b, "  },\n")
		case "valueError":
			if argList != "" {
				fmt.Fprintf(&b, "  async %s(%s, fetchOpts) {\n", m.Name, argList)
				fmt.Fprintf(&b, "    return await rpcCall(%q, [%s], fetchOpts);\n", m.Name, callList)
			} else {
				fmt.Fprintf(&b, "  async %s(fetchOpts) {\n", m.Name)
				fmt.Fprintf(&b, "    return await rpcCall(%q, [], fetchOpts);\n", m.Name)
			}
			fmt.Fprintf(&b, "  },\n")
		}
	}
	fmt.Fprintf(&b, "};\n")
	appendSSEClientJS(&b)
	return b.String()
}

func renderClientDTS(typeName string, methods []signatureMethod, sse []config.SSEEventDecl) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by \"sash bind\"; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "export interface SashBindingsConfig {\n")
	fmt.Fprintf(&b, "  apiBase?: string;\n")
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "export interface SashFetchOpts {\n")
	fmt.Fprintf(&b, "  signal?: AbortSignal;\n")
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "export function configureSashBindings(c: SashBindingsConfig): void;\n")
	fmt.Fprintf(&b, "export const devApiBaseURL: string;\n\n")
	fmt.Fprintf(&b, "export function eventsURL(): string;\n\n")
	fmt.Fprintf(&b, "export const %s: {\n", typeName)
	for _, m := range methods {
		var parts []string
		for i := range m.ParamTypes {
			parts = append(parts, fmt.Sprintf("a%d: %s", i, goWireTypeToTS(m.ParamTypes[i])))
		}
		parts = append(parts, "fetchOpts?: SashFetchOpts")
		retTS := "void"
		if m.ResultKind == "valueError" {
			retTS = goWireTypeToTS(m.ResultType)
		}
		fmt.Fprintf(&b, "  %s(%s): Promise<%s>;\n", m.Name, strings.Join(parts, ", "), retTS)
	}
	fmt.Fprintf(&b, "};\n")
	appendSSEDTS(&b, sse)
	return b.String()
}

func goWireTypeToTS(t types.Type) string {
	if t == nil {
		return "unknown"
	}
	switch tt := t.(type) {
	case *types.Alias:
		return goWireTypeToTS(tt.Rhs())
	case *types.Named:
		return goWireTypeToTS(tt.Underlying())
	case *types.Pointer:
		inner := goWireTypeToTS(tt.Elem())
		if inner == "unknown" {
			return "unknown"
		}
		return inner + " | null"
	case *types.Slice:
		return "(" + goWireTypeToTS(tt.Elem()) + ")[]"
	case *types.Array:
		return "(" + goWireTypeToTS(tt.Elem()) + ")[]"
	case *types.Map:
		if !isJSONObjectMapKey(tt.Key()) {
			return "unknown"
		}
		return "Record<string, " + goWireTypeToTS(tt.Elem()) + ">"
	case *types.Struct:
		return "object"
	case *types.Interface:
		return "unknown"
	case *types.Basic:
		switch tt.Kind() {
		case types.String, types.UntypedString:
			return "string"
		case types.Bool, types.UntypedBool:
			return "boolean"
		case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
			types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64,
			types.Uintptr, types.UntypedInt, types.UntypedRune:
			return "number"
		case types.Float32, types.Float64, types.UntypedFloat:
			return "number"
		case types.Complex64, types.Complex128, types.UnsafePointer:
			return "unknown"
		default:
			return "unknown"
		}
	default:
		return "unknown"
	}
}
