// Code generated by "sash bind"; DO NOT EDIT.

package sashbindings

import (
	"net/http"

	api "github.com/zackarysantana/sash/examples/solid-vite/api"

	"github.com/zackarysantana/sash/src/sashrpc"
)

const EmbeddedMountPath = "/api/sash"

const DevListenAddr = "127.0.0.1:9350"

func RPCHandler(recv *api.API) http.Handler {
	h, err := sashrpc.Handler(recv)
	if err != nil {
		panic(err)
	}
	return sashrpc.WithCORS(h)
}

func MountEmbedded(mux *http.ServeMux, recv *api.API) {
	mux.Handle(EmbeddedMountPath+"/API/", http.StripPrefix(EmbeddedMountPath+"/API", RPCHandler(recv)))
}

func MountDevRoutes(mux *http.ServeMux, recv *api.API) {
	mux.Handle("/API/", http.StripPrefix("/API", RPCHandler(recv)))
}
