// Code generated by "sash bind"; DO NOT EDIT.

export interface SashBindingsConfig {
  apiBase?: string;
}

export interface SashFetchOpts {
  signal?: AbortSignal;
}

export function configureSashBindings(c: SashBindingsConfig): void;
export const devApiBaseURL: string;

export function eventsURL(): string;

export const API: {
  Message(fetchOpts?: SashFetchOpts): Promise<string>;
  WaitFiveSeconds(fetchOpts?: SashFetchOpts): Promise<void>;
};

export interface SashSSESessionOpts {
  url?: string;
}

export interface SashSSEPayloadMap {
  "tick": {
    sec: number;
  };
}

export type SashSSEEventName = keyof SashSSEPayloadMap;

export interface SashSSESession {
  readonly source: EventSource;
  listenJSON<N extends keyof SashSSEPayloadMap>(event: N, handler: (payload: SashSSEPayloadMap[N], ev: MessageEvent) => void): () => void;
  close(): void;
}

export function createSashSSESession(opts?: SashSSESessionOpts): SashSSESession;
