// Code generated by "sash bind"; DO NOT EDIT.

let __sashCfg = {};

export function configureSashBindings(c) {
  __sashCfg = { ...__sashCfg, ...c };
}

const embeddedMount = "/api/sash";
export const devApiBaseURL = "http://127.0.0.1:9349";

function rpcUrl(method) {
  const base = (__sashCfg.apiBase ?? "").replace(/\/+$/, "");
  const suffix = `/API/${method}`;
  if (base !== "") {
    return `${base}${suffix}`;
  }
  return `${embeddedMount}${suffix}`;
}

export function eventsURL() {
  const base = (__sashCfg.apiBase ?? "").replace(/\/+$/, "");
  if (base !== "") {
    return `${base}/events`;
  }
  return `${embeddedMount}/events`;
}

async function rpcCall(method, args, fetchOpts) {
  const res = await fetch(rpcUrl(method), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ args }),
    signal: fetchOpts?.signal,
  });
  let body = {};
  try {
    body = await res.json();
  } catch {
    body = {};
  }
  if (!res.ok || body.error) {
    throw new Error(body.error ?? res.statusText);
  }
  if ("result" in body) {
    return body.result;
  }
  return undefined;
}

async function __sashAutoConfigureRuntime() {
  if (typeof globalThis.location === "undefined") {
    return;
  }
  if (__sashCfg.apiBase) {
    return;
  }
  if (typeof import.meta !== "undefined" && import.meta.env && import.meta.env.DEV === true) {
    configureSashBindings({ apiBase: devApiBaseURL });
    return;
  }
  try {
    const res = await fetch(new URL("/api/sash/API/Add", globalThis.location.href), { method: "OPTIONS" });
    if (res.ok) {
      return;
    }
  } catch (_) {}
  configureSashBindings({ apiBase: devApiBaseURL });
}

await __sashAutoConfigureRuntime();

export const API = {
  async Add(a0, fetchOpts) {
    return await rpcCall("Add", [a0], fetchOpts);
  },
  async Get(fetchOpts) {
    return await rpcCall("Get", [], fetchOpts);
  },
};

export function createSashSSESession(opts = {}) {
  const url = opts.url ?? eventsURL();
  const es = new EventSource(url);
  es.onerror = () => {};
  return {
    source: es,
    listenJSON(eventName, handler) {
      const fn = (ev) => {
        let payload;
        try {
          payload = JSON.parse(ev.data);
        } catch {
          return;
        }
        handler(payload, ev);
      };
      es.addEventListener(eventName, fn);
      return () => es.removeEventListener(eventName, fn);
    },
    close() {
      es.close();
    },
  };
}
