// Code generated by "sash bind"; DO NOT EDIT.

export interface SashBindingsConfig {
  apiBase?: string;
}

export interface SashFetchOpts {
  signal?: AbortSignal;
}

export function configureSashBindings(c: SashBindingsConfig): void;
export const devApiBaseURL: string;

export function eventsURL(): string;

export const API: {
  Add(a0: number, fetchOpts?: SashFetchOpts): Promise<number>;
  Get(fetchOpts?: SashFetchOpts): Promise<number>;
};

export interface SashSSESessionOpts {
  url?: string;
}

export interface SashSSESession {
  readonly source: EventSource;
  listenJSON<E extends string, T>(event: E, handler: (payload: T, ev: MessageEvent) => void): () => void;
  close(): void;
}

export function createSashSSESession(opts?: SashSSESessionOpts): SashSSESession;
